// Console photo for each backend slug (files in public/images/consoles).
// Consoles missing here show Placeholder.png. Add a line when you add a photo.
export const CONSOLE_IMAGES: Record<string, string> = {
  "batlexp-g350": "BattleXP G350.avif",
  "cubexx": "CubeXX.png",
  "mangmi-air-x": "Mangmi-Air-X.png",
  "miniloong-pocket": "Miniloong-pocket.png",
  "miyoo-flip": "miyoo-flip.png",
  "miyoo-mini-flip": "miyoo-mini-flip.png",
  "miyoo-mini-plus": "MiyooMiniPlus.png",
  "odin-3-pro": "odin-3-pro.png",
  "r36h": "R36H.webp",
  "r36s": "R36S-PURPLE-LISTING-DONE-01.png",
  "retroid-pocket-5": "Retroid-Pocket-5.png",
  "retroid-pocket-6": "Retroid-Pocket-6.webp",
  "retroid-pocket-duo": "Retroid Pocket Duo.png",
  "retroid-pocket-duo-lite": "Retroid Pocket Duo Lite.png",
  "retroid-pocket-nova": "Retroid Pocket Nova.png",
  "rg-477m-12g": "RG-477M-12G.png",
  "rg-477m-8g": "RG-477M-8G.png",
  "rg-arc-s": "RG-ARC-S.png",
  "rg-cube": "RG-Cube.png",
  "rg-rotate-metal": "RG-Rotate-metal.webp",
  "rg-rotate-plastic": "RG-Rotate-plastic.png",
  "rg-slide": "RG-Slide.webp",
  "rg-vita": "RG Vita.webp",
  "rg-vita-pro": "RG-Vita-Pro.webp",
  "rg28xx": "RG28XX.webp",
  "rg34xx": "RG34XX.webp",
  "rg34xxsp": "RG34XXSP.webp",
  "rg353ps": "RG353PS.avif",
  "rg35xx-h": "RG35XX H.avif",
  "rg35xx-pro": "RG35XX Pro.png",
  "rg35xxsp": "RG35XXSP.avif",
  "rg405m": "RG405M.webp",
  "rg405v": "RG405V.png",
  "rg406h": "RG406H.png",
  "rg406v": "RG406V.png",
  "rg40xx-h": "RG40XX H.png",
  "rg40xx-v": "RG40XX-V.avif",
  "rg476h": "RG476H.webp",
  "rg477v": "RG477V.webp",
  "rg505": "RG505.png",
  "rg556": "RG556.webp",
  "rg557": "RG557.webp",
  "rg55g1-4gb": "RG55G1-4GB.png",
  "rgds": "RGDS.png",
  "rgsp": "RGSP.png",
  "thor-base": "AYN Thor Base.png",
  "trimui-brick": "trimui-brick.png",
  "trimui-brick-pro": "Trimui-Brick-Pro.webp",
  "trimui-smart-pro": "Trimui-Smart-Pro.webp",
  "zero-40": "magicx-zero-40.avif",
};

export function consoleImage(slug: string): string {
  const file = CONSOLE_IMAGES[slug] ?? "Placeholder.png";
  return `/images/consoles/${encodeURIComponent(file)}`;
}
